# Repository type: memory, xml, json, database, text file
Repository = database
# The URL of the SQLite database file.
DatabaseURL = jdbc:sqlite:C:\\Users\\ursac\\IdeaProjects\\Assignment4-5\\data\\init_database.sql

# Paths to files
Patients = data/patients.xml
Appointments = data/appointments.xml
